version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6060:6060'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  db:
    driver: local
